### ISSUE TITLE
The Errors section should not be present in the response if there were no errors.

### ISSUE THREAD

**Issue by drjokepu** [joemcbride/graphql-dotnet#22]
Currently, even if no errors occurred during the execution of a query, the "errors" property of the response is populated with an empty array. This is a violation of the GraphQL specification:

> ### [7.2 Response Format](https://facebook.github.io/graphql/#sec-Response-Format)
>
> [...]
> 
> If the operation encountered any errors, the response map must contain an entry with key errors. The value of this entry is described in the “Errors” section. If the operation completed without encountering any errors, this entry must not be present.
> 
> [...]

The current response does not work with the latest version of Relay, as it assumes that if the "errors" property is present (even if it's just an empty array) the query has failed with an error.

**Comment by joemcbride** [comment]
Thanks for this report.  Have you verified that nulling out the errors property makes relay happy?

**Comment by drjokepu** [comment]
Yes, the following works with Relay:
```C#
var result = executer.ExecuteAsync(schema, null, request.Query, null, null).Result;
var resultJson = writer.Write(result);
var response = Newtonsoft.Json.Linq.JObject.Parse(resultJson);
response.Remove("errors");
var responseJson = response.ToString();
```

**Comment by joemcbride** [comment]
Instead of removing it from the json, can you just null out the property?  I need to know if we need different return objects for error vs. non error or if just nulling out the property works.

```
var result = executer.ExecuteAsync(schema, null, request.Query, null, null).Result;
result.Errors = null;
var resultJson = writer.Write(result);
...
```

**Comment by drjokepu** [comment]
The following does **not** appear to work with the latest version of Relay:

```C#
var result = executer.ExecuteAsync(schema, null, request.Query, "", null).Result;
if (!result.Errors.Any())
{
    result.Errors = null;
}
var resultJson = writer.Write(result);
```

It fails with the following error:
> Cannot read property 'map' of null
> RelayPendingQueryTracker.js:162

A combination of assigning null to it if it's empty and an attribute such as `[JsonProperty(NullValueHandling = NullValueHandling.Ignore)]` on the `ExecutionResult.Errors` property should take care of the situation.

**Comment by joemcbride** [comment]
Awesome, thanks!
